name: Deployment

on:
  workflow_call:
    inputs:
        environment:
          required: true
          type: string
        production:
          required: false
          type: boolean
          default: false
        domain:
          required: false
          type: string
          default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ inputs.environment }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: | # ADD ALL ENV VARIABLES HERE
          yarn
          DATABASE_URL="${{ secrets.DATABASE_URL}}" \
          FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY}}" \
          FIREBASE_CLIENT_EMAIL="${{ secrets.FIREBASE_CLIENT_EMAIL}}" \
          FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID}}" \
          AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID}}" \
          AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY}}" \
          AWS_BUCKET="${{ secrets.AWS_BUCKET}}" \
          AWS_BUCKET_CATEGORIES_IMAGES="${{ secrets.AWS_BUCKET_CATEGORIES_IMAGES}}" \
          AWS_BUCKET_PRODUCTS_IMAGES="${{ secrets.AWS_BUCKET_PRODUCTS_IMAGES}}" \
          AWS_BUCKET_PRODUCTS_TECHNICAL_FILE="${{ secrets.AWS_BUCKET_PRODUCTS_TECHNICAL_FILE}}" \
          AWS_BUCKET_TRANSFER_RECEIPTS="${{ secrets.AWS_BUCKET_TRANSFER_RECEIPTS}}" \
          AWS_BUCKET_ORDER_INVOICE="${{ secrets.AWS_BUCKET_ORDER_INVOICE}}" \
          AWS_BUCKET_ORDER_SIGNED_INVOICE="${{ secrets.AWS_BUCKET_ORDER_SIGNED_INVOICE}}" \
          TOKEN_BCRA="${{ secrets.TOKEN_BCRA }}" \
          ENV="${{ secrets.ENV }}" \
          yarn build
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_TEAM_NAME }}
          PRODUCTION: ${{ inputs.production }}
          ALIAS_DOMAINS: |
            https://${{ inputs.domain }}${{ secrets.APP_DOMAIN }}