name: Deploy Develop
on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-develop:
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    with:
      environment: develop
      domain: dev.